# Generated by Django 4.2.5 on 2024-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_volcano_eruption_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_volcanoes',
            field=models.ManyToManyField(blank=True, to='myapp.volcano'),
        ),
    ]
